services:
  - type: web
    name: pyq-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Isko Render dashboard mein update karna hoga safety ke liye
